# Generated by Django 5.1.1 on 2024-09-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_coment_author_comment_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
    ]
